"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, CheckCircle2, ChevronRight, CircleAlert, ClipboardPaste, Clock3, Copy, ExternalLink, FileSpreadsheet, HelpCircle, Link2, ListTodo, Search, Send, Settings2, Sparkles, Users } from "lucide-react";
import { toast } from "sonner";
import { Toaster } from "@/components/ui/sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";

type View = "queue" | "children" | "schedule" | "review" | "history";
type SlotStatus = "처리 대기" | "후보 확인 중" | "추가 확인 필요" | "연결 완료";
type NoticeStatus = "미안내" | "안내 완료";
type Slot = { id:string; date:string; time:string; type:string; therapist:string; candidates:number; status:SlotStatus; assignedParticipant?:string|null; noticeStatus?:NoticeStatus; noticeText?:string; assignedAt?:string|null; noticeCompletedAt?:string|null };
type Candidate = { id:string; waiting:number; recent:string; type:string; available:string; availableTimes:string[]; active:boolean };
type WaitItem = { id:string; type:string; availability:string; since:string; recent:string; active?:boolean };
type ParticipantForm = { id:string; type:string; availability:string; since:string; recent:string; active:boolean };
type ParsedAbsence = { date:string; time:string; type:string; therapist:string; safeText:string };
type ScheduleEntry = { id:string; date:string; weekday:string; department:string; therapistId:string; therapistName:string; startTime:string; endTime:string; treatmentCode:string; importBatch:string };
type ScheduleImportPreview = { fileName:string; date:string; weekday:string; entries:ScheduleEntry[]; therapists:Array<{id:string;name:string;department:string}>; warnings:string[] };
type ParticipantRequest = { id:string; participantId:string; submittedAt:string; desiredDate:string; therapyTypes:string; morningTimes:string; afternoonTimes:string; status:string; note:string };
type ParticipantImportPreview = { fileName:string; participants:WaitItem[]; requests:ParticipantRequest[]; warnings:string[] };

const initialSlots: Slot[] = [
  { id:"S-104", date:"9월 3일", time:"10:00–10:30", type:"작업치료", therapist:"OT-03", candidates:3, status:"처리 대기" },
  { id:"S-105", date:"9월 3일", time:"11:30–12:00", type:"물리치료", therapist:"PT-07", candidates:2, status:"처리 대기" },
  { id:"S-106", date:"9월 3일", time:"14:00–14:30", type:"작업치료", therapist:"OT-06", candidates:0, status:"추가 확인 필요" },
  { id:"S-107", date:"9월 4일", time:"09:30–10:00", type:"물리치료", therapist:"PT-02", candidates:4, status:"처리 대기" },
];
const candidates: Candidate[] = [
  { id:"아동 가", waiting:18, recent:"8월 12일", type:"작업치료", available:"화·목 09:00–12:00", availableTimes:["09:30","10:00","10:30","11:00","11:30"], active:true },
  { id:"아동 나", waiting:11, recent:"연결 이력 없음", type:"작업치료", available:"평일 10:00–15:00", availableTimes:["10:00","10:30","11:00","11:30","13:00","13:30","14:00","14:30"], active:true },
  { id:"아동 다", waiting:7, recent:"8월 28일", type:"작업치료", available:"목 09:00–11:00", availableTimes:["09:00","09:30","10:00","10:30"], active:true },
  { id:"아동 라", waiting:16, recent:"8월 21일", type:"물리치료", available:"월·수·금 13:00–16:00", availableTimes:["13:00","13:30","14:00","14:30","15:00","15:30"], active:true },
  { id:"아동 마", waiting:9, recent:"연결 이력 없음", type:"물리치료", available:"평일 09:00–12:00", availableTimes:["09:00","09:30","10:00","10:30","11:00","11:30"], active:true },
  { id:"아동 바", waiting:5, recent:"8월 30일", type:"물리치료", available:"목 10:30–14:30", availableTimes:["10:30","11:00","11:30","13:00","13:30","14:00"], active:true },
];
const initialWaitlist: WaitItem[] = [
  { id:"아동 가", type:"작업치료", availability:"화·목 09:00–12:00", since:"8월 16일", recent:"8월 12일" },
  { id:"아동 나", type:"작업치료", availability:"평일 10:00–15:00", since:"8월 23일", recent:"없음" },
  { id:"아동 다", type:"작업치료", availability:"목 09:00–11:00", since:"8월 27일", recent:"8월 28일" },
  { id:"아동 라", type:"물리치료", availability:"월·수·금 13:00–16:00", since:"8월 18일", recent:"8월 21일" },
];
const nav = [
  { id:"queue" as View, label:"처리 대기", icon:ListTodo },
  { id:"children" as View, label:"대기 아동 관리", icon:Users },
  { id:"schedule" as View, label:"치료 일정", icon:CalendarDays },
  { id:"review" as View, label:"추가 확인 필요", icon:CircleAlert },
  { id:"history" as View, label:"연결·안내 내역", icon:Send },
];
const sessionTimes = ["08:30","09:00","09:30","10:00","10:30","11:00","11:30","13:00","13:30","14:00","14:30","15:00","15:30","16:00","16:30","17:00","17:30"];
const defaultNoticeTemplate = "안녕하세요. 학령기치료실 입니다.\n{날짜} {시간}에 {치료종류} 추가 배정 되어 안내드립니다.\n감사합니다.";
function statusClass(status: SlotStatus) { return {"처리 대기":"status-blue","후보 확인 중":"status-purple","추가 확인 필요":"status-orange","연결 완료":"status-green"}[status]; }

export default function Home() {
  function importCsv(e:React.ChangeEvent<HTMLInputElement>){void previewParticipantCsv(e)}
  const [view,setView] = useState<View>("queue"); const [slots,setSlots] = useState(initialSlots); const [active,setActive] = useState<Slot|null>(null); const [selected,setSelected] = useState<Candidate|null>(null);
  const [confirmOpen,setConfirmOpen] = useState(false); const [absenceOpen,setAbsenceOpen] = useState(false); const [message,setMessage] = useState(""); const [parsed,setParsed] = useState(false); const [parsedData,setParsedData] = useState<ParsedAbsence|null>(null); const [query,setQuery] = useState("");
  const [participantRequests,setParticipantRequests] = useState<ParticipantRequest[]>([]); const [participantImportPreview,setParticipantImportPreview] = useState<ParticipantImportPreview|null>(null);
  useEffect(()=>{if(participantOpen&&!editingParticipant)setParticipantForm({id:"",type:"",availability:"",since:"",recent:"",active:true})},[participantOpen,editingParticipant]);
  useEffect(()=>{if(!participantImportPreview)return;const ok=window.confirm(`${participantImportPreview.fileName}\n\n대기 아동 ${participantImportPreview.participants.length}명, 희망 일정 ${participantImportPreview.requests.length}건을 반영합니다. 원본 이름·생년월일은 저장하지 않습니다.`);if(ok)void applyParticipantImport();else setParticipantImportPreview(null)},[participantImportPreview]);
  const [dateRange,setDateRange] = useState("오늘"); const [timeRange,setTimeRange] = useState("정확히 일치"); const [scope,setScope] = useState("전체 대기 아동"); const [csvCount,setCsvCount] = useState(0); const [waitData,setWaitData] = useState(initialWaitlist); const [rulesOpen,setRulesOpen] = useState(false); const [participantOpen,setParticipantOpen] = useState(false); const [editingParticipant,setEditingParticipant] = useState<string|null>(null); const [participantForm,setParticipantForm] = useState<ParticipantForm>({id:"",type:"작업치료",availability:"",since:"2026-09-03",recent:"없음",active:true}); const [templateOpen,setTemplateOpen] = useState(false); const [noticeTemplate,setNoticeTemplate] = useState(defaultNoticeTemplate); const [templateDraft,setTemplateDraft] = useState(defaultNoticeTemplate); const [resultSlot,setResultSlot] = useState<Slot|null>(null); const [scheduleMode,setScheduleMode] = useState<"all"|"empty">("all"); const [scheduleData,setScheduleData] = useState<ScheduleEntry[]>([]); const [schedulePreview,setSchedulePreview] = useState<ScheduleImportPreview|null>(null); const fileRef = useRef<HTMLInputElement>(null); const scheduleFileRef = useRef<HTMLInputElement>(null);
  const queue = useMemo(()=>slots.filter(s=>s.status!=="연결 완료"),[slots]); const completeCount = slots.filter(s=>s.status==="연결 완료").length;
  const matchedCandidates = useMemo(()=>{if(!active)return[];const start=active.time.slice(0,5);const toMinutes=(t:string)=>Number(t.slice(0,2))*60+Number(t.slice(3,5));const tolerance=timeRange==="±1시간"?60:timeRange==="±30분"?30:0;return candidates.filter(c=>c.type===active.type&&(scope!=="활성 아동만"||c.active)&&c.availableTimes.some(t=>Math.abs(toMinutes(t)-toMinutes(start))<=tolerance)).sort((a,b)=>b.waiting-a.waiting)},[active,timeRange,scope]);
  const activeScheduleDate = useMemo(()=>scheduleData.map(e=>e.date).sort().at(-1)??"2026-09-03",[scheduleData]);
  const scheduleTherapists = useMemo(()=>{const seen=new Map<string,{id:string;name:string;department:string}>();scheduleData.filter(e=>e.date===activeScheduleDate).forEach(e=>seen.set(e.therapistId,{id:e.therapistId,name:e.therapistName,department:e.department}));return [...seen.values()]},[scheduleData,activeScheduleDate]);
  useEffect(()=>{fetch("/api/state").then(r=>r.ok?r.json():null).then(data=>{if(data?.slots?.length){const demoTimes:Record<string,string>={"S-104":"10:00–10:30","S-105":"11:30–12:00","S-106":"14:00–14:30","S-107":"09:30–10:00"};setSlots(data.slots.map((s:{id:string;therapyType:string;candidateCount:number},i:number)=>({...s,time:demoTimes[s.id]??(s as {time:string}).time,type:s.therapyType,candidates:s.candidateCount,id:s.id||`S-${i}`})))}if(data?.participants?.length)setWaitData(data.participants.map((p:{id:string;therapyType:string;availability:string;waitingSince:string;recentConnection:string;active:boolean})=>({id:p.id,type:p.therapyType,availability:p.availability,since:p.waitingSince,recent:p.recentConnection,active:p.active})));if(data?.settings?.notice_template){setNoticeTemplate(data.settings.notice_template);setTemplateDraft(data.settings.notice_template)}if(data?.scheduleEntries?.length)setScheduleData(data.scheduleEntries)}).catch(()=>undefined)},[]);
  async function saveSlot(slot:Slot,action:string,detail:string){try{await fetch("/api/state",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"slot",slot,audit:{slotId:slot.id,action,detail}})})}catch{toast.error("화면에는 반영했지만 서버 저장을 확인하지 못했습니다.")}}
  function openCandidates(slot:Slot){ if(slot.candidates===0){ setView("review"); toast("후보가 없어 추가 확인 목록으로 이동했습니다."); return; } setActive(slot); setSelected(null); setSlots(v=>v.map(s=>s.id===slot.id?{...s,status:"후보 확인 중"}:s)); }
  function hold(){ if(!active) return; const next={...active,status:"추가 확인 필요" as SlotStatus}; setSlots(v=>v.map(s=>s.id===active.id?next:s)); void saveSlot(next,"HOLD","후보 조건 추가 확인 필요"); setActive(null); setSelected(null); toast("추가 확인 필요로 보류했습니다."); }
  function renderNotice(slot:Slot,template=noticeTemplate){return template.replaceAll("{날짜}",slot.date).replaceAll("{시간}",slot.time).replaceAll("{치료종류}",slot.type).replaceAll("{치료사}",slot.therapist)}
  function confirm(){ if(!active||!selected) return;const noticeText=renderNotice(active);const next:Slot={...active,status:"연결 완료",assignedParticipant:selected.id,noticeStatus:"미안내",noticeText,assignedAt:new Date().toISOString(),noticeCompletedAt:null};setSlots(v=>v.map(s=>s.id===active.id?next:s));void saveSlot(next,"CONFIRM",`${selected.id} 연결 · 규칙: 가능 시간/치료 유형 일치, 대기 경과일 순`);setConfirmOpen(false);setActive(null);setSelected(null);setResultSlot(next);toast.success("회기를 연결하고 안내문을 생성했습니다.");}
  async function saveNoticeTemplate(){if(!templateDraft.trim()){toast.error("기본문구를 입력해 주세요.");return}try{const response=await fetch("/api/state",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"setting",setting:{key:"notice_template",value:templateDraft}})});if(!response.ok)throw new Error();setNoticeTemplate(templateDraft);setTemplateOpen(false);toast.success("안내문 기본문구를 저장했습니다.")}catch{toast.error("기본문구를 저장하지 못했습니다.")}}
  async function copyNotice(){if(!resultSlot?.noticeText)return;try{await navigator.clipboard.writeText(resultSlot.noticeText);toast.success("안내문을 복사했습니다.")}catch{toast.error("복사하지 못했습니다. 안내문을 직접 선택해 주세요.")}}
  function completeNotice(){if(!resultSlot)return;const next:Slot={...resultSlot,noticeStatus:"안내 완료",noticeCompletedAt:new Date().toISOString()};setSlots(v=>v.map(s=>s.id===next.id?next:s));setResultSlot(next);void saveSlot(next,"NOTICE_COMPLETE",`${next.assignedParticipant} 안내 완료`);toast.success("안내 완료로 기록했습니다.")}
  function parseAbsence(){ if(!message.trim()){toast.error("결석 문자를 붙여넣어 주세요.");return}const safe=message.replace(/01[016789]-?\d{3,4}-?\d{4}/g,"[연락처 제거]").replace(/[가-힣]{2,4}(?=\s*(아동|어머님|보호자|입니다))/g,"[이름 제거]");const type=/PT|물리/i.test(safe)?"물리치료":"작업치료";const therapist=safe.match(/(?:OT|PT)-?\d{1,2}/i)?.[0].toUpperCase().replace(/^(OT|PT)(\d)/,"$1-$2")??(type==="작업치료"?"OT-05":"PT-05");const hm=safe.match(/(오전|오후)?\s*(\d{1,2})\s*시(?:\s*(\d{1,2})\s*분)?/);let hour=hm?Number(hm[2]):15;if(hm?.[1]==="오후"&&hour<12)hour+=12;const minute=hm?.[3]?Number(hm[3]):0;const endMin=minute+30;const endHour=hour+Math.floor(endMin/60);const time=`${String(hour).padStart(2,"0")}:${String(minute).padStart(2,"0")}–${String(endHour).padStart(2,"0")}:${String(endMin%60).padStart(2,"0")}`;setParsedData({date:"2026-09-03",time,type,therapist,safeText:safe});setParsed(true);toast.success("식별정보를 가린 뒤 회기 정보를 추출했습니다.")}
  function registerAbsence(){ if(!parsedData)return;const next:Slot={id:`S-${Date.now().toString().slice(-6)}`,date:"9월 3일",time:parsedData.time,type:parsedData.type,therapist:parsedData.therapist,candidates:2,status:"처리 대기"};setSlots(v=>[next,...v]);void saveSlot(next,"CREATE_FROM_MESSAGE","익명화된 결석 문장에서 빈 회기 등록");setAbsenceOpen(false);setParsed(false);setParsedData(null);setMessage("");setView("queue");toast.success("빈 회기를 처리 대기에 등록했습니다.")}
  async function previewScheduleCsv(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;try{const buffer=await file.arrayBuffer();let text="";try{text=new TextDecoder("utf-8",{fatal:true}).decode(buffer)}catch{text=new TextDecoder("euc-kr").decode(buffer)}const rows=parseCsv(text);if(rows.length<2||rows[0][1]!=="일자"||rows[0][3]!=="부서"||rows[0][5]!=="치료사")throw new Error("현황판 CSV 형식을 확인할 수 없습니다.");const batch=`${Date.now()}`;const entries:ScheduleEntry[]=[];const therapistMap=new Map<string,{id:string;name:string;department:string}>();const warnings:string[]=[];let date="",weekday="";for(const row of rows.slice(1)){if(!row[1]||!row[4]||!row[5])continue;const rowDate=row[1].slice(0,10);date ||= rowDate;weekday ||= row[2];if(rowDate!==date){warnings.push("여러 날짜가 포함되어 첫 날짜만 반영됩니다.");continue}therapistMap.set(row[4],{id:row[4],name:row[5],department:row[3]});for(let col=7;col<row.length;col++){const code=row[col]?.trim();if(!code)continue;const minutes=8*60+(col-7)*10;const start=`${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;if(!sessionTimes.includes(start)){warnings.push(`${row[5]} ${start}은 운영 시간 또는 30분 시작 기준에서 제외되었습니다.`);continue}const endMinutes=minutes+30;const end=`${String(Math.floor(endMinutes/60)).padStart(2,"0")}:${String(endMinutes%60).padStart(2,"0")}`;entries.push({id:`${date}|${row[4]}|${start}`,date,weekday,department:row[3],therapistId:row[4],therapistName:row[5],startTime:start,endTime:end,treatmentCode:code,importBatch:batch})}}if(!date||!entries.length)throw new Error("반영할 치료 일정이 없습니다.");if(therapistMap.size!==14)warnings.push(`치료사가 14명이 아닌 ${therapistMap.size}명입니다.`);setSchedulePreview({fileName:file.name,date,weekday,entries,therapists:[...therapistMap.values()],warnings:[...new Set(warnings)]})}catch(error){toast.error(error instanceof Error?error.message:"CSV를 읽지 못했습니다.")}}
  async function applyScheduleImport(){if(!schedulePreview)return;try{const response=await fetch("/api/state",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"schedule_import",scheduleImport:{date:schedulePreview.date,entries:schedulePreview.entries}})});if(!response.ok){const data=await response.json().catch(()=>null);throw new Error(data?.error??"저장하지 못했습니다.")}setScheduleData(current=>[...current.filter(e=>e.date!==schedulePreview.date),...schedulePreview.entries]);toast.success(`${schedulePreview.date} 치료 일정 ${schedulePreview.entries.length}건을 반영했습니다.`);setSchedulePreview(null)}catch(error){toast.error(error instanceof Error?error.message:"치료 일정을 저장하지 못했습니다.")}}
  async function previewParticipantCsv(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value="";if(!file)return;try{const buffer=await file.arrayBuffer();let text="";try{text=new TextDecoder("utf-8",{fatal:true}).decode(buffer)}catch{text=new TextDecoder("euc-kr").decode(buffer)}const rows=parseCsv(text);if(rows.length<2)throw new Error("CSV에 데이터 행이 없습니다.");const today="2026-09-03", map=new Map<string,WaitItem>(), requests:ParticipantRequest[]=[], warnings:string[]=[];for(const [i,row] of rows.slice(1).entries()){const name=(row[1]||"").trim(),dob=(row[2]||"").trim(),desired=(row[3]||"").trim();if(!name&&!dob&&!desired)continue;if(!name||!dob||!desired){warnings.push(`${i+2}행: 이름·생년월일·희망 날짜가 없어 제외했습니다.`);continue}const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`${name}|${dob}`));const hex=[...new Uint8Array(digest)].slice(0,4).map(v=>v.toString(16).padStart(2,"0")).join("").toUpperCase(),id=`아동-${hex}`;const dateMatch=desired.match(/(\d{4})\.\s*(\d{1,2})\.\s*(\d{1,2})/);const date=dateMatch?`${dateMatch[1]}-${String(dateMatch[2]).padStart(2,"0")}-${String(dateMatch[3]).padStart(2,"0")}`:desired;const types=[...(row[4]||"").matchAll(/물리|작업|언어|감각/g)].map(m=>m[0]==="물리"?"물리치료":m[0]==="작업"?"작업치료":m[0]);const therapyTypes=[...new Set(types.length?types:["치료 유형 확인 필요"])];const morning=(row[5]||"").trim(),afternoon=(row[6]||"").trim(),note=(row[7]||"").trim();let status=note.includes("완료")?"처리 완료":note.includes("공지")?"안내 완료":/(자리없음|타임수초과)/.test(note)?"추가 확인 필요":note.includes("취소")?"신청 취소":date<today?"만료":"처리 대기";const submitted=(row[0]||"").slice(0,10).replace(/[./]/g,"-")||date;const request={id:`${id}|${date}|${i}`,participantId:id,submittedAt:submitted,desiredDate:date,therapyTypes:therapyTypes.join(", "),morningTimes:morning,afternoonTimes:afternoon,status,note};requests.push(request);const existing=map.get(id);map.set(id,{id,type:existing?[...new Set(`${existing.type}, ${therapyTypes.join(", ")}`.split(", ").filter(Boolean))].join(", "):therapyTypes.join(", "),availability:[morning&&`오전 ${morning}`,afternoon&&`오후 ${afternoon}`].filter(Boolean).join(" · ")||"시간 미지정",since:existing&&existing.since<submitted?existing.since:submitted,recent:existing?.recent??"없음",active:existing?.active!==false&&!["만료","신청 취소"].includes(status)})}if(!map.size)throw new Error("반영할 유효한 행이 없습니다.");setParticipantImportPreview({fileName:file.name,participants:[...map.values()],requests,warnings:[...new Set(warnings)]})}catch(error){toast.error(error instanceof Error?error.message:"CSV를 읽지 못했습니다.")}}
  async function applyParticipantImport(){if(!participantImportPreview)return;const payload={participants:participantImportPreview.participants.map(p=>({id:p.id,type:p.type,availability:p.availability,since:p.since,recent:p.recent,active:p.active!==false})),requests:participantImportPreview.requests};try{const response=await fetch("/api/state",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"participants_import",participantsImport:payload})});if(!response.ok)throw new Error();setWaitData(current=>[...current.filter(c=>!payload.participants.some(p=>p.id===c.id)),...participantImportPreview.participants]);setParticipantRequests(current=>[...current,...participantImportPreview.requests]);setCsvCount(participantImportPreview.requests.length);toast.success(`대기 아동 ${payload.participants.length}명 · 희망 일정 ${payload.requests.length}건을 반영했습니다.`);setParticipantImportPreview(null)}catch{toast.error("대기 아동 CSV를 저장하지 못했습니다.")}}
  function openParticipantForm(item?:WaitItem){setEditingParticipant(item?.id??null);setParticipantForm({id:item?.id??`아동 ${String.fromCharCode(65+waitData.length)}`,type:item?.type??"작업치료",availability:item?.availability??"",since:item?.since??"2026-09-03",recent:item?.recent??"없음",active:item?.active??true});setParticipantOpen(true)}
  async function saveParticipant(){const p=participantForm;if(!p.id.trim()||!p.availability.trim()||!p.since){toast.error("가명 ID, 가능 시간, 대기 시작일은 필수입니다.");return}if(!editingParticipant&&waitData.some(item=>item.id===p.id.trim())){toast.error("같은 가명 ID가 이미 등록되어 있습니다.");return}const next={...p,id:p.id.trim(),availability:p.availability.trim(),recent:p.recent.trim()||"없음"};try{const response=await fetch("/api/state",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"participant",participant:next})});if(!response.ok)throw new Error();setWaitData(current=>editingParticipant?current.map(item=>item.id===editingParticipant?next:item):[...current,next]);setParticipantOpen(false);toast.success(editingParticipant?`${next.id} 정보를 수정했습니다.`:`${next.id}을 대기 명단에 등록했습니다.`)}catch{toast.error("아동 정보를 저장하지 못했습니다.")}}

  return <div className="app-shell"><Toaster position="top-center" richColors />
    <header className="global-header"><div className="brand"><span className="brand-mark"><Link2 size={21}/></span><div><strong>이어:봄</strong><small>LinkSpring</small></div></div><div className="global-context"><strong>아동 치료 회기 연결 시스템</strong><span>2026년 9월 3일 목요일</span></div><div className="top-actions"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="회기 또는 아동 검색"/></label><Button onClick={()=>setAbsenceOpen(true)}><ClipboardPaste size={17}/>결석 문자 등록</Button></div></header>
    <aside className="sidebar"><nav aria-label="주요 메뉴">{nav.map(item=><button key={item.id} className={view===item.id?"nav-active":""} onClick={()=>setView(item.id)}><item.icon size={19}/><span>{item.label}</span>{item.id==="queue"&&queue.length>0?<em>{queue.length}</em>:null}</button>)}</nav><div className="side-bottom"><button onClick={()=>{setTemplateDraft(noticeTemplate);setTemplateOpen(true)}}><Settings2 size={18}/>안내문 기본문구</button><button onClick={()=>setRulesOpen(true)}><HelpCircle size={18}/>운영 규칙 안내</button><div className="privacy-note"><span>가상 데이터</span><p>실명과 진료정보를 사용하지 않습니다.</p></div></div></aside>
    <main className="main"><div className="content-frame"><header className="page-header"><div><p>현재 작업</p><h1>{nav.find(n=>n.id===view)?.label}</h1></div><span>코디네이터 01</span></header>
      {view==="queue"&&<section><div className="summary-grid"><Summary label="처리 대기" value={queue.filter(s=>s.status==="처리 대기").length} tone="blue" icon={<Clock3/>}/><Summary label="연결 가능한 회기" value={queue.filter(s=>s.candidates>0).length} tone="purple" icon={<Users/>}/><Summary label="추가 확인 필요" value={queue.filter(s=>s.status==="추가 확인 필요").length} tone="orange" icon={<CircleAlert/>}/><Summary label="오늘 연결 완료" value={completeCount} tone="green" icon={<CheckCircle2/>}/></div><div className="section-head"><div><h2>처리할 빈 회기</h2><p>발생 시간순입니다. 한 건씩 확인해 주세요.</p></div><Badge variant="outline">{queue.length}건 남음</Badge></div><div className="queue-list">{queue.filter(s=>!query||`${s.type} ${s.time} ${s.therapist}`.includes(query)).map((slot,i)=><button className="queue-card" key={slot.id} onClick={()=>openCandidates(slot)}><span className="queue-index">{String(i+1).padStart(2,"0")}</span><div className="queue-date"><strong>{slot.date}</strong><span>{slot.time}</span></div><div className="therapy-pill">{slot.type}</div><div className="candidate-count"><Users size={17}/><strong>{slot.candidates}</strong><span>명 후보</span></div><span className={`status ${statusClass(slot.status)}`}>{slot.status}</span><ChevronRight className="arrow" size={20}/></button>)}</div></section>}
      {view==="children"&&<section><div className="section-head"><div><h2>대기 아동</h2><p>가명 ID·치료 유형·가능 시간·대기 시작일을 직접 관리합니다.</p></div><div className="inline-actions"><input ref={fileRef} hidden type="file" accept=".csv" onChange={importCsv}/><Button variant="outline" onClick={()=>fileRef.current?.click()}><FileSpreadsheet size={17}/>CSV 불러오기</Button><Button onClick={()=>openParticipantForm()}><Users size={17}/>아동 직접 등록</Button></div></div>{csvCount>0&&<div className="import-banner"><CheckCircle2 size={18}/>CSV {csvCount}행 검증·반영 완료 · 필수값 기본 보정 <Button size="sm" onClick={()=>setCsvCount(0)}>확인</Button></div>}<div className="table-card"><Table><TableHeader><TableRow><TableHead>가명 ID</TableHead><TableHead>치료 유형</TableHead><TableHead>가능 시간</TableHead><TableHead>대기 시작일</TableHead><TableHead>최근 연결</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{waitData.map(w=><TableRow key={w.id}><TableCell className="font-semibold">{w.id}</TableCell><TableCell>{w.type}</TableCell><TableCell>{w.availability}</TableCell><TableCell>{w.since}</TableCell><TableCell>{w.recent}</TableCell><TableCell><Button variant="ghost" size="sm" onClick={()=>openParticipantForm(w)}>수정</Button></TableCell></TableRow>)}</TableBody></Table></div></section>}
      {view==="schedule"&&<section><div className="section-head"><div><h2>{scheduleData.length?`${activeScheduleDate} 치료 일정`:"당일 치료 일정"}</h2><p>익명 현황판 CSV의 예약 코드를 반영합니다. 08:30–12:00 / 13:00–18:00, 회기당 30분</p></div><div className="inline-actions"><input ref={scheduleFileRef} hidden type="file" accept=".csv,text/csv" onChange={previewScheduleCsv}/><Button variant="outline" onClick={()=>scheduleFileRef.current?.click()}><FileSpreadsheet size={17}/>당일 시간표 CSV 불러오기</Button>{scheduleData.length?<Button variant={scheduleMode==="empty"?"default":"outline"} onClick={()=>setScheduleMode(v=>v==="all"?"empty":"all")}><Settings2 size={17}/>{scheduleMode==="empty"?"전체 일정 보기":"빈 회기만 보기"}</Button>:null}</div></div>{scheduleData.length?<><div className="schedule-import-summary"><CheckCircle2 size={18}/><span>익명 시간표 반영 완료</span><strong>{scheduleTherapists.length}명 · 예약 {scheduleData.filter(e=>e.date===activeScheduleDate).length}건</strong></div><div className="therapist-schedule"><div className="schedule-row schedule-header"><strong>치료사</strong>{sessionTimes.map(t=><span key={t}>{t}</span>)}</div>{scheduleTherapists.map(therapist=><div className="schedule-row" key={therapist.id}><strong className={therapist.department.includes("작업")?"ot-label":"pt-label"} title={therapist.id}>{therapist.name}</strong>{sessionTimes.map(time=>{const entry=scheduleData.find(e=>e.date===activeScheduleDate&&e.therapistId===therapist.id&&e.startTime===time);const openSlot=slots.find(s=>s.status!=="연결 완료"&&(s.therapist===therapist.name||s.therapist===therapist.id)&&s.time.startsWith(time));const hidden=scheduleMode==="empty"&&!openSlot;return <button key={time} disabled={hidden||(!entry&&!openSlot)} className={hidden?"session-hidden":openSlot?"session-empty":entry?"session-booked":"session-unassigned"} onClick={()=>openSlot?openCandidates(openSlot):entry?toast(`${therapist.name} ${time} · ${entry.treatmentCode}`):undefined} aria-label={`${therapist.name} ${time} ${openSlot?"빈 회기":entry?entry.treatmentCode:"미배정"}`}><span>{hidden?"":openSlot?"빈 회기":entry?.treatmentCode??"—"}</span></button>})}</div>)}</div><div className="schedule-legend"><span><i className="legend-booked"/>예약 코드</span><span><i className="legend-empty"/>결석으로 발생한 빈 회기</span><span><i className="legend-unassigned"/>미배정</span><span>점심시간 12:00–13:00 제외</span></div></>:<div className="schedule-upload-empty"><FileSpreadsheet/><strong>당일 익명 시간표를 불러와 주세요.</strong><p>CSV는 화면에서 해석되며 원본 파일은 저장하지 않습니다.</p><Button onClick={()=>scheduleFileRef.current?.click()}>CSV 파일 선택</Button></div>}</section>}
      {view==="review"&&<section><div className="section-head"><div><h2>추가 확인 필요</h2><p>후보가 없거나 즉시 결정하지 못한 회기입니다.</p></div></div><div className="review-list">{slots.filter(s=>s.status==="추가 확인 필요").map(s=><article key={s.id}><div className="review-icon"><CircleAlert/></div><div><strong>{s.date} · {s.time}</strong><p>{s.type} · {s.therapist}</p></div><Badge className="ml-auto" variant="outline">담당: 코디네이터 01</Badge><Button variant="outline" onClick={()=>openCandidates({...s,candidates:3})}>조건 수정·재검색</Button></article>)}</div></section>}
      {view==="history"&&<section><div className="section-head"><div><h2>연결·안내 내역</h2><p>연결 결과와 보호자 안내 여부를 이어서 처리합니다.</p></div><Badge variant="outline">완료 {completeCount}건</Badge></div><div className="history-list">{slots.filter(s=>s.status==="연결 완료").length?slots.filter(s=>s.status==="연결 완료").map(s=><article key={s.id}><div><strong>{s.date} · {s.time}</strong><p>{s.type} · {s.therapist} · {s.assignedParticipant??"아동 정보 없음"}</p></div><Badge className={s.noticeStatus==="안내 완료"?"notice-done":"notice-pending"}>{s.noticeStatus??"미안내"}</Badge><Button variant="outline" onClick={()=>setResultSlot(s)}>결과 열기</Button></article>):<div className="empty-history"><CheckCircle2/><strong>아직 연결 완료 내역이 없습니다.</strong><p>회기를 연결하면 안내 업무가 이곳에 기록됩니다.</p></div>}</div></section>}
    </div></main>
    <Dialog open={!!active} onOpenChange={o=>{if(!o){setActive(null);setSelected(null)}}}><DialogContent className="candidate-dialog"><DialogHeader><DialogTitle>연결 후보 확인</DialogTitle><DialogDescription>{active?.date} · {active?.time} · {active?.type} · {active?.therapist}</DialogDescription></DialogHeader><div className="filter-row"><Select value={timeRange} onValueChange={setTimeRange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="정확히 일치">정확히 일치</SelectItem><SelectItem value="±30분">±30분</SelectItem><SelectItem value="±1시간">±1시간</SelectItem></SelectContent></Select><Select value={dateRange} onValueChange={setDateRange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="오늘">오늘</SelectItem><SelectItem value="3일">3일</SelectItem><SelectItem value="7일">7일</SelectItem></SelectContent></Select><Select value={scope} onValueChange={setScope}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="전체 대기 아동">전체 대기 아동</SelectItem><SelectItem value="활성 아동만">활성 아동만</SelectItem></SelectContent></Select><Button variant="outline" onClick={()=>toast(`${matchedCandidates.length}명의 후보를 확인했습니다.`)}><Search size={16}/>재검색</Button></div><div className="rule-note"><Sparkles size={17}/><span>가능 시간·치료 유형이 일치한 후보를 <strong>대기 경과일이 긴 순</strong>으로 표시합니다.</span></div><div className="candidate-list">{matchedCandidates.length?matchedCandidates.map((c,i)=><button key={c.id} className={selected?.id===c.id?"candidate selected":"candidate"} onClick={()=>setSelected(c)}><span className="rank">{i+1}</span><div><strong>{c.id}</strong><small>{c.available}</small></div><dl><div><dt>대기 경과</dt><dd>{c.waiting}일</dd></div><div><dt>최근 연결</dt><dd>{c.recent}</dd></div><div><dt>치료 적합</dt><dd className="fit">일치</dd></div></dl><p>{i===0?"가능 시간 일치 · 대기 기간 최장":"가능 시간 및 치료 유형 일치"}</p></button>):<div className="candidate-empty"><CircleAlert/><strong>조건에 맞는 후보가 없습니다.</strong><p>시간 범위를 넓히거나 추가 확인 필요로 보류하세요.</p></div>}</div><div className="dialog-footer"><Button variant="outline" onClick={hold}><CircleAlert size={17}/>추가 확인 필요</Button><Button disabled={!selected} onClick={()=>setConfirmOpen(true)}>선택한 아동 연결<ChevronRight size={17}/></Button></div></DialogContent></Dialog>
    <AlertDialog open={confirmOpen} onOpenChange={setConfirmOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>이 회기를 연결할까요?</AlertDialogTitle><AlertDialogDescription>확정하면 안내문 초안이 생성됩니다. 실제 발송 완료는 별도로 기록합니다.</AlertDialogDescription></AlertDialogHeader><div className="confirm-grid"><span>빈 회기<strong>{active?.date} {active?.time}</strong></span><span>치료 종류<strong>{active?.type}</strong></span><span>선택 아동<strong>{selected?.id}</strong></span></div><AlertDialogFooter><AlertDialogCancel>다시 확인</AlertDialogCancel><AlertDialogAction onClick={confirm}>이 아동에게 연결하고 안내문 생성</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Sheet open={!!resultSlot} onOpenChange={o=>{if(!o)setResultSlot(null)}}><SheetContent className="result-sheet"><SheetHeader><SheetTitle>연결 및 안내 결과</SheetTitle><SheetDescription>연결 후 보호자 안내까지 한 흐름에서 완료합니다.</SheetDescription></SheetHeader>{resultSlot&&<div className="result-body"><div className="result-status"><CheckCircle2/><div><strong>회기 연결 완료</strong><span>{resultSlot.noticeStatus??"미안내"}</span></div></div><dl className="result-details"><div><dt>빈 회기</dt><dd>{resultSlot.date} {resultSlot.time}</dd></div><div><dt>치료 정보</dt><dd>{resultSlot.type} · {resultSlot.therapist}</dd></div><div><dt>선택 아동</dt><dd>{resultSlot.assignedParticipant}</dd></div><div><dt>처리 담당자</dt><dd>코디네이터 01</dd></div><div><dt>처리 시각</dt><dd>{resultSlot.assignedAt?new Date(resultSlot.assignedAt).toLocaleString("ko-KR"):"기록 없음"}</dd></div></dl><div className="notice-block"><div><strong>보호자 안내문</strong><Badge variant="outline">개인정보 미포함</Badge></div><Textarea value={resultSlot.noticeText??""} onChange={e=>setResultSlot({...resultSlot,noticeText:e.target.value})} rows={7}/><Button onClick={copyNotice} className="w-full"><Copy size={17}/>안내문 복사</Button><Button variant="outline" disabled title="기관 메시지 API 연결 후 활성화"><ExternalLink size={17}/>기관 연락 채널 열기 · API 연결 예정</Button></div><div className="notice-check"><span>안내 상태</span><strong className={resultSlot.noticeStatus==="안내 완료"?"done":"pending"}>{resultSlot.noticeStatus??"미안내"}</strong></div>{resultSlot.noticeStatus!=="안내 완료"?<Button size="lg" onClick={completeNotice}><CheckCircle2 size={18}/>보호자 안내 완료로 기록</Button>:<div className="notice-complete"><CheckCircle2/><div><strong>안내 업무가 완료되었습니다.</strong><span>{resultSlot.noticeCompletedAt?new Date(resultSlot.noticeCompletedAt).toLocaleString("ko-KR"):"완료 시각 기록됨"}</span></div></div>}</div>}</SheetContent></Sheet>
    <Dialog open={absenceOpen} onOpenChange={setAbsenceOpen}><DialogContent className="absence-dialog"><DialogHeader><DialogTitle>결석 문자 등록</DialogTitle><DialogDescription>원문은 저장되지 않으며, 식별정보를 가린 뒤 회기 정보만 추출합니다.</DialogDescription></DialogHeader><div className="parse-grid"><div><Label htmlFor="absence">결석 문자 원문</Label><Textarea id="absence" rows={8} value={message} onChange={e=>setMessage(e.target.value)} placeholder="예: 오늘 오후 3시 20분 OT-05 치료에 참석하기 어렵습니다."/><p className="safe-copy"><CheckCircle2 size={15}/>서버 전송 전 이름과 연락처를 제거합니다.</p><Button onClick={parseAbsence} className="w-full"><Sparkles size={17}/>안전하게 정보 추출</Button></div><div className={parsed?"parsed active":"parsed"}><span>추출 결과</span>{parsedData?<><Field label="날짜" value={parsedData.date}/><Field label="시간" value={parsedData.time}/><Field label="치료 종류" value={parsedData.type}/><Field label="담당 치료사" value={parsedData.therapist}/><p className="safe-preview">익명화 문장: {parsedData.safeText}</p><Button onClick={registerAbsence} className="w-full">확인하고 빈 회기 등록</Button></>:<div className="empty-parse"><ClipboardPaste/><p>문자를 붙여넣고<br/>정보 추출을 실행하세요.</p></div>}</div></div></DialogContent></Dialog>
    <Dialog open={!!schedulePreview} onOpenChange={o=>{if(!o)setSchedulePreview(null)}}><DialogContent className="schedule-import-dialog"><DialogHeader><DialogTitle>당일 치료 일정 반영</DialogTitle><DialogDescription>기존 동일 날짜 일정은 확인 후 새 CSV 내용으로 교체됩니다.</DialogDescription></DialogHeader>{schedulePreview&&<><div className="import-file-name"><FileSpreadsheet/><div><strong>{schedulePreview.fileName}</strong><span>{schedulePreview.date} · {schedulePreview.weekday}요일</span></div></div><div className="import-metrics"><div><span>치료사</span><strong>{schedulePreview.therapists.length}명</strong></div><div><span>물리치료</span><strong>{schedulePreview.therapists.filter(t=>t.department.includes("물리")).length}명</strong></div><div><span>작업치료</span><strong>{schedulePreview.therapists.filter(t=>t.department.includes("작업")).length}명</strong></div><div><span>예약 회기</span><strong>{schedulePreview.entries.length}건</strong></div></div>{schedulePreview.warnings.length?<div className="import-warnings"><CircleAlert/><div><strong>확인할 내용</strong>{schedulePreview.warnings.map(w=><p key={w}>{w}</p>)}</div></div>:<div className="import-valid"><CheckCircle2/>열 구조와 회기 시간을 확인했습니다.</div>}<div className="import-policy"><strong>반영 원칙</strong><p>예약 코드만 일정에 저장합니다. 빈 셀은 ‘미배정’으로 표시하며 자동으로 빈 회기에 등록하지 않습니다. 빈 회기는 결석 등록을 통해 별도로 생성됩니다.</p></div><div className="template-actions"><Button variant="outline" onClick={()=>setSchedulePreview(null)}>취소</Button><Button onClick={applyScheduleImport}>이 일정으로 교체</Button></div></>}</DialogContent></Dialog>
    <Dialog open={participantOpen} onOpenChange={setParticipantOpen}><DialogContent className="participant-dialog"><DialogHeader><DialogTitle>{editingParticipant?"대기 아동 정보 수정":"대기 아동 직접 등록"}</DialogTitle><DialogDescription>후보 비교와 연결 판단에 사용하는 정보를 입력합니다.</DialogDescription></DialogHeader><div className="participant-form"><label><span>가명 ID <em>필수</em></span><Input value={participantForm.id} onChange={e=>setParticipantForm(f=>({...f,id:e.target.value}))} placeholder="예: 아동 A" disabled={!!editingParticipant}/></label><label><span>치료 유형 <em>필수</em></span><Select value={participantForm.type} onValueChange={value=>setParticipantForm(f=>({...f,type:value}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="작업치료">작업치료</SelectItem><SelectItem value="물리치료">물리치료</SelectItem></SelectContent></Select></label><label className="form-wide"><span>등록한 가능 시간 <em>필수</em></span><Input value={participantForm.availability} onChange={e=>setParticipantForm(f=>({...f,availability:e.target.value}))} placeholder="예: 화·목 09:00–12:00"/><small>요일과 시간을 함께 입력해 주세요.</small></label><label><span>대기 시작일 <em>필수</em></span><Input type="date" value={participantForm.since} onChange={e=>setParticipantForm(f=>({...f,since:e.target.value}))}/></label><label><span>최근 연결 이력</span><Input value={participantForm.recent} onChange={e=>setParticipantForm(f=>({...f,recent:e.target.value}))} placeholder="예: 8월 12일 / 없음"/></label><label><span>대기 상태</span><Select value={participantForm.active?"active":"inactive"} onValueChange={value=>setParticipantForm(f=>({...f,active:value==="active"}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">활성</SelectItem><SelectItem value="inactive">일시 중지</SelectItem></SelectContent></Select></label></div><div className="template-actions"><Button variant="outline" onClick={()=>setParticipantOpen(false)}>취소</Button><Button onClick={saveParticipant}>{editingParticipant?"수정 저장":"대기 아동 등록"}</Button></div></DialogContent></Dialog>
    <Dialog open={templateOpen} onOpenChange={setTemplateOpen}><DialogContent className="template-dialog"><DialogHeader><DialogTitle>안내문 기본문구 설정</DialogTitle><DialogDescription>연결 완료 시 회기 정보가 변수 위치에 자동으로 입력됩니다.</DialogDescription></DialogHeader><div className="template-editor"><div><Label htmlFor="notice-template">기본문구</Label><Textarea id="notice-template" rows={7} value={templateDraft} onChange={e=>setTemplateDraft(e.target.value)}/><div className="template-variables"><span>사용 가능한 변수</span>{["{날짜}","{시간}","{치료종류}","{치료사}"].map(v=><button key={v} type="button" onClick={()=>setTemplateDraft(t=>`${t}${t.endsWith(" ")||t.endsWith("\n")?"":" "}${v}`)}>{v}</button>)}</div></div><div className="template-preview"><span>미리보기</span><p>{renderNotice({...initialSlots[0],date:"9월 3일",time:"15:00–15:30",type:"물리치료"},templateDraft)}</p></div></div><div className="template-actions"><Button variant="outline" onClick={()=>setTemplateDraft(defaultNoticeTemplate)}>기본문구로 되돌리기</Button><Button onClick={saveNoticeTemplate}>저장</Button></div></DialogContent></Dialog>
    <Dialog open={rulesOpen} onOpenChange={setRulesOpen}><DialogContent><DialogHeader><DialogTitle>이어:봄 운영 원칙</DialogTitle><DialogDescription>AI와 규칙, 사람의 역할을 명확히 분리합니다.</DialogDescription></DialogHeader><div className="principle-list"><article><Sparkles/><div><strong>AI는 문장을 구조화합니다</strong><p>결석 문장에서 회기 정보를 추출하지만 배정에는 관여하지 않습니다.</p></div></article><article><Settings2/><div><strong>규칙은 후보를 정렬합니다</strong><p>가능 시간·치료 유형이 맞는 후보를 대기 경과일 순으로 제시합니다.</p></div></article><article><Users/><div><strong>사람이 최종 확정합니다</strong><p>코디네이터가 최근 연결 이력과 현장 상황을 확인하고 책임 있게 결정합니다.</p></div></article></div></DialogContent></Dialog>
  </div>;
}
function Summary({label,value,tone,icon}:{label:string,value:number,tone:string,icon:React.ReactNode}){return <article className={`summary ${tone}`}><span>{icon}</span><div><p>{label}</p><strong>{value}<small>건</small></strong></div></article>}
function Field({label,value}:{label:string,value:string}){return <label className="field"><span>{label}</span><Input defaultValue={value}/></label>}
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell="";let quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v!==""))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(v=>v!==""))rows.push(row);const cleaned=rows.map((r,i)=>r.map((v,j)=>i===0&&j===0?v.replace(/^\uFEFF/,""):v.trim()));const h=cleaned[0]??[];if(h.includes("아동 이름")){const index=(...names:string[])=>names.map(n=>h.indexOf(n)).find(i=>i>=0)??-1;const order=[index("타임스탬프"),index("아동 이름"),index("아동 생년월일"),index("보강치료 희망 날짜"),index("치료"),index("오전"),index("오후"),index("비고")];return [h,...cleaned.slice(1).map(r=>order.map(i=>i>=0?r[i]??"":""))]}return cleaned}
